# Generated by Django 5.1.5 on 2025-01-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_native_name_remove_products_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='id_image',
        ),
    ]
