# Generated by Django 5.1.5 on 2025-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_products_image_remove_seller_id_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
