# Generated by Django 5.1.5 on 2025-01-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='id_image',
            field=models.ImageField(null=True, upload_to='id_images'),
        ),
    ]
