# Generated by Django 4.2.5 on 2025-01-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_total_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
