# Generated by Django 4.2.5 on 2025-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
